---
name: trek_place
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.6.7+22
  path: ^1.6.2
  path_provider: ^1.6.27
  provider: ^4.3.2+4
  sqflite: ^1.3.2+4
  location: ^3.2.4
  google_maps_flutter: ^1.2.0
  http: ^0.12.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
